services:
  api:
    build: .
    container_name: server_FastAPI_Prac4
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
